version: '3.4'
services:
  client:
    container_name: astro_focus_kit_client
    build: 
      context: ..
      dockerfile: ./astro-focus-kit-env/client.Dockerfile
    ports:
      - 5173:5173
    env_file:
      - .env
    volumes:
      - ../astro-focus-kit-client:/app
      - /app/node_modules
    networks:
      - astro_focus_kit_network
    command: npm run dev
  server:
    container_name: astro_focus_kit_server
    build: 
      context: ..
      dockerfile: ./astro-focus-kit-env/server.Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=db
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    volumes:
      - ../astro-focus-kit-server:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/package*.json
    networks:
      - astro_focus_kit_network
    command: npm run dev
  db-astro:
    image: mongo:4.1.8-xenial
    container_name: astro_focus_kit_db
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:  
      - dbdata:/data/db   
    networks:
      - astro_focus_kit_network 
networks:
  astro_focus_kit_network:
      driver: bridge

volumes:
  dbdata:
  node_modules: